/* ====================================================================
   Copyright (C) 2015 Procom Data Services Inc.

   This file is part of the TownSuite DataMigrator Tool.
	
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   For additional information, visit
   the website https://github.com/TownSuite/DataMigrator.
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dapper;

namespace DataMigrator
{
    public class Generate
    {

        public void Execute()
        {
            System.IO.File.WriteAllText(Program.SaveFile, "// Data Generated by TownSuite DataMigrator" + System.Environment.NewLine);

            Program.Write("using System;" + System.Environment.NewLine);
            Program.Write("using System.Text;" + System.Environment.NewLine);
            Program.Write("using FluentMigrator;" + System.Environment.NewLine);
            Program.Write("" + System.Environment.NewLine);
            Program.Write("namespace WebDbMigrations" + System.Environment.NewLine);
            Program.Write("{" + System.Environment.NewLine);
            Program.Write("    [Profile(\"nunit\")]" + System.Environment.NewLine);
            Program.Write("    public partial class NunitData : FluentMigrator.Migration" + System.Environment.NewLine);
            Program.Write("    {" + System.Environment.NewLine);
            Program.Write("        public override void Up()" + System.Environment.NewLine);
            Program.Write("        {" + System.Environment.NewLine);
            Program.Write("            CustomData();" + System.Environment.NewLine);
            Program.Write(System.Environment.NewLine);
            var tables = new Tables.Filtered(Program.IgnoreTables);

            foreach (var table in tables.Values)
            {
                Scan(table);
            }
            Program.Write("        }" + System.Environment.NewLine);
            Program.Write("        public override void Down()" + System.Environment.NewLine);
            Program.Write("        {" + System.Environment.NewLine);
            Program.Write("        }" + System.Environment.NewLine);
            Program.Write("    }" + System.Environment.NewLine);
            Program.Write("}" + System.Environment.NewLine);

        }

        private void Scan(string table)
        {
            Program.Write(System.Environment.NewLine);

            if (Program.UpdateTables.Contains(table))
            {
                var update = new Update(table);
                update.Execute();
            }
            else
            {
                var insert = new Insert(table);
                insert.Execute();
            }
        }






    }
}
